spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snapy
    username: username
    password: password

jwt:
  secret-key: jwt-secret-key

snapy:
  s3:
    bucket: bucket-name
  cloudfront:
    url: https://changeme.cloudfront.net

google:
  oauth:
    web:
      client-id: your-google-web-client-id
      client-secret: your-google-web-client-secret
    ios:
      client-id: your-google-ios-client-id