server:
  port: 8080

spring:
  config:
    import: optional:application-secret.yml

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

google:
  oauth:
    web:
      redirect-uri: http://localhost:8080/auth/google/callback

frontend:
  url: http://localhost:5173

