spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snapy
    username: username
    password: password

jwt:
  secret-key: jwt-secret-key

snapy:
  s3:
    bucket: bucket-name
  cloudfront:
    url: https://changeme.cloudfront.net

google:
  oauth:
    web:
      client-id: your-google-web-client-id
      client-secret: your-google-web-client-secret
      redirect-uri: http://localhost:8080/auth/google/callback
    ios:
      client-id: your-google-ios-client-id

frontend:
  url: http://localhost:5173

grpc:
  server:
    host: 127.0.0.1
    port: 5000